### ISSUE TITLE
go modules should be added.

### ISSUE THREAD

**Issue by Alex-liutao** [bahlo/go-styleguide#14]
I think adding go modules to "Dependency management" would be a good idea

**Comment by bahlo** [comment]
It is a good idea, but we should wait until it's not experimental anymore. Leaving this open until then

**Comment by d1str0** [comment]
I believe Go modules are now official and no longer experimental with Go 1.12

**Comment by bahlo** [comment]
Thanks @Alex-liutao and @d1str0!
